credentials:
  - username: mark.harris
    email: mark.harris@interfor.com
    name: Mark Harris
    password: abc # to be replaced with hashed password
  - username: mdh
    email: markdavidharris@gmail.com
    name: Mark David Harris
    password: def # to be replaced with hashed password
cookie:
  expiry_days: 30
  key: somesignaturekey # must be string
  name: IFPVFAAuth
preauthorized:
  - markdavidharris@gmail.com
